# Generated by Django 5.2.8 on 2025-11-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secundarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("futebol", "Futebol"),
                            ("basquete", "Basquete"),
                            ("volei", "Vôlei"),
                            ("tenis", "Tênis"),
                            ("corrida", "Corrida"),
                            ("natação", "Natação"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
