# Generated by Django 5.2.8 on 2025-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secundarios", "0004_searchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RemoveField(
            model_name="resposta",
            name="post",
        ),
        migrations.RemoveField(
            model_name="resposta",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Resposta",
        ),
        migrations.DeleteModel(
            name="SearchLog",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
