# Generated by Django 6.0 on 2025-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secundarios", "0007_remove_resposta_post_remove_resposta_autor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("autor", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=200)),
                ("tag", models.CharField(blank=True, max_length=50)),
                ("conteudo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.DeleteModel(
            name="Local",
        ),
    ]
